alias ls='eza -lah --icons --group-directories-first --sort=ext'
alias lst='eza -a --tree --icons --group-directories-first --sort=ext'
alias v='nvim'
alias gog='lgogdownloader'
alias grep='rg --color=auto'
alias fgrep='rg -F --color=auto'
alias egrep='egrep --color=auto'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias cat='batcat --paging=never --theme=gruvbox-material-dark'
alias fd='fdfind'
