alias ls='eza -laah --icons=auto --git --group-directories-first --sort=Extension --follow-symlinks'
alias lsd='eza -laahD --icons=auto --sort=Extension --follow-symlinks --show-symlinks' 
alias lsf='eza -laahf --icons=auto --git --group-directories-first --sort=Extension --follow-symlinks --show-symlinks'
alias v='nvim'
alias gog='lgogdownloader'
alias grep='rg --color=auto'
alias fgrep='rg -F --color=auto'
alias egrep='egrep --color=auto'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias cat='batcat --paging=never --theme=gruvbox-material-dark'
alias fd='fdfind'
