[flags]
tree = true
show_table_scroll_position = true
enable_gpu = true
group_processes = true

[[row]]
   ratio=30
   [[row.child]]
     [[row.child.child]]
       type="mem"
     [[row.child.child]]
       type="net"
   [[row.child]]
     type="cpu"
[[row]]
   ratio=40
   [[row.child]]
     ratio=2
     [[row.child.child]]
       ratio=4
       type="temp"
     [[row.child.child]]
       ratio=1
       type="disk"
   [[row.child]]
     ratio=5
     type="proc"
     default=true
